name: E2E

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    services:

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        working-directory: 10xWarehouseAstro/astro-app
        run: npm ci

      - name: Install Playwright (Chromium)
        working-directory: 10xWarehouseAstro/astro-app
        run: npx playwright install --with-deps chromium

      - name: Start backend (docker-compose)
        run: docker compose up -d

      - name: Wait for backend
        run: |
          for i in {1..40}; do
            curl -fsS http://localhost:8080/ || true
            if curl -fsS http://localhost:8080/organizations || curl -fsS http://localhost:8080/; then
              echo "Backend is up"; break
            fi
            sleep 3
          done

      - name: Run E2E
        working-directory: 10xWarehouseAstro/astro-app
        run: npm run test:e2e -- --reporter=github

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: 10xWarehouseAstro/astro-app/playwright-report
          if-no-files-found: ignore