name: E2E

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      PLAYWRIGHT_BACKEND_URL: http://localhost:8080/api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        working-directory: 10xWarehouseAstro/astro-app
        run: npm ci

      - name: Install Playwright (Chromium)
        working-directory: 10xWarehouseAstro/astro-app
        run: npx playwright install --with-deps chromium

      - name: Start backend (docker-compose)
        run: docker compose up -d

      - name: Wait for backend
        run: |
          echo "Waiting for backend to be ready..."
          for i in {1..60}; do
            # Check if backend is responding (even 404/401 means it's up)
            if curl -f -s -o /dev/null -w "%{http_code}" http://localhost:8080/ | grep -qE "^(200|404|401|403)$"; then
              echo "Backend is responding"
              # Verify it's actually the API by checking a simple endpoint
              status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/organizations || echo "000")
              if [ "$status" != "000" ]; then
                echo "Backend API is ready (status: $status)"
                break
              fi
            fi
            echo "Attempt $i/60: Backend not ready yet..."
            sleep 2
          done

      - name: Run E2E
        working-directory: 10xWarehouseAstro/astro-app
        env:
          CI: true
        run: npm run test:e2e -- --reporter=line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: 10xWarehouseAstro/astro-app/playwright-report
          retention-days: 7
          if-no-files-found: ignore